# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: Hosted VS2017
steps:
- task: NodeTool@0
  displayName: 'Use Node 12.x'
  inputs:
    versionSpec: 12.x

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: build
  inputs:
    command: custom
    verbose: false
    customCommand: 'run ng -- build -c production'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Visual Studio Enterprise (4cacb210-354d-4c71-9f3b-1368a6b47f61)'
    appType: 'webApp'
    appName: ballistics
    package: '$(System.DefaultWorkingDirectory)/dist'
    deploymentMethod: 'auto'
