apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}-service
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
  selector:
    app: {{.Chart.Name}}
  type: LoadBalancer
